version: '2'
services:
  zookeeper:
    image: quay.io/debezium/zookeeper:${DEBEZIUM_VERSION}
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
    networks:
     - mssqlserver_default
  kafka:
    image: quay.io/debezium/kafka:${DEBEZIUM_VERSION}
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
    networks:
     - mssqlserver_default 
#  sqlserver:
#    image: mcr.microsoft.com/mssql/server:2019-latest
#    ports:
#     - 1433:1433
#    environment:
#     - ACCEPT_EULA=Y
#     - MSSQL_PID=Developer
#     - SA_PASSWORD=Password!
#     - MSSQL_AGENT_ENABLED=true
  connect:
    image: quay.io/debezium/connect:${DEBEZIUM_VERSION}
    ports:
     - 8083:8083
    links:
     - kafka
     # - sqlserver
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses
    networks:
     - mssqlserver_default
networks:
  mssqlserver_default:
    external: true